# Site Name/Title
name: Jung Kook AT40 Requests

# Welcome Tagline
tagline: Hello there! Welcome to the AT40 Request links page for Jung Kook. Feel free to click away and make your requests. 

# Profile Image URL
Image_URL: http://www.gravatar.com/avatar/79699862899006b32a2ca0199e862b54?s=400

# Website Background Image
Cover_Image: https://source.unsplash.com/random

# Request Links
links:
    
    # Z100 New York - Left & Right
  - Name: Z100 New York | Left & Right
    URL: https://tinyurl.com
    Username: AT40-NewYorkNY-Z100-LnR
    Color: '#3b5998'
    Icon-Class:

    # Z100 New York - Stay Alive
  - Name: Z100 New York | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-NewYorkNY-Z100-SA 
    Color: '#DD2A7B'
    Icon-Class: 

    # STAR 94.1 Atlanta - Left and Right
  - Name: STAR 94.1 Atlanta | Left and Right
    URL: https://tinyurl.com
    Username: AT40-AtlantaGA-941-LnR 
    Color: '#1DA1F2'
    Icon-Class: 

    # STAR 94.1 Atlanta - Stay Alive
  - Name: STAR 94.1 Atlanta | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-AtlantaGA-941-SA 
    Color: '#f1c40f'
    Icon-Class: 
    
    # 96.7 KISS FM Austin - Left and Right
  - Name: 96.7 KISS FM Austin | Left and Right
    URL: https://tinyurl.com
    Username: AT40-AustinTX-967-LnR 
    Color: '#2867B2'
    Icon-Class: 

    # 96.7 KISS FM Austin - Stay Alive
  - Name: 96.7 KISS FM Austin | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-AustinTX-967-SA 
    Color: '#ff0000'
    Icon-Class:

    # KISS 108 Boston - Left and Right
  - Name: KISS 108 Boston | Left and Right
    URL: https://tinyurl.com
    Username: AT40-BostonMA-108-LnR
    Color: '#6e5494'
    Icon-Class:

    # KISS 108 Boston - Stay Alive
  - Name: KISS 108 Boston | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-BostonMA-108-SA
    Color: '#e17055'
    Icon-Class: 

    # 102.7 KIIS FM Los Angeles - Left and Right
  - Name: 102.7 KIIS FM Los Angeles | Left and Right
    URL: https://tinyurl.com
    Username: AT40-LosAngelesCA-1027-LnR 
    Icon-Class: 
    Color: '#9147fe'

    # 102.7 KIIS FM Los Angeles - Stay Alive
  - Name: 102.7 KIIS FM Los Angeles | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-LosAngelesCA-1027-SA
    Icon-Class: 
    Color: '#1ab7ea'

    # MIX 96.9 Phoenix - Left and Right
  - Name: MIX 96.9 Phoenix | Left and Right
    URL: https://tinyurl.com
    Username: AT40-PhoenixAZ-969-LnR
    Color: '#006AFF'
    Icon-Class: 

    # MIX 96.9 Phoenix - Stay Alive
  - Name: MIX 96.9 Phoenix | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-PhoenixAZ-969-SA
    Color: '#FF4500'
    Icon-Class:

    # Z100 Portland - Left and Right
  - Name: Z100 Portland | Left and Right
    URL: https://tinyurl.com
    Username: AT40-PortandOR-Z100-LnR
    Color: '#25d366'
    Icon-Class: 

    # Z100 Portland - Stay Alive
  - Name: Z100 Portland | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-PortandOR-Z100-SA
    Color: '#0088cc'
    Icon-Class:

    # KC 101 Hamden - Left and Right
  - Name: KC 101 Hamden | Left and Right
    URL: https://tinyurl.com
    Username: AT40-HamdenCT-101-LnR
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class:

    # KC 101 Hamden - Stay Alive
  - Name: KC 101 Hamden | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-HamdenCT-101-SA 
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class:

    # Twitter - Jung Kook Radio
  - Name: Twitter
    URL: https://twitter.com
    Username: JungkookRadio
    Icon-Class: fab fa-twitter
    Color: '#d94869'
    Text_Color: '#ffffff'

    # Contact
  - Name: Email
    URL: 'mailto:hol_1012@yahoo.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

# Footer - Can be removed entirely by removing 'Yes' or commenting out the code line.
# footer: 'Yes'

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /HIGHonLIFE1012.github.io

# Default Markdown Engine
markdown: kramdown
