# Site Name/Title
name: Jung Kook AT40 Requests

# Welcome Tagline
tagline: Hello there! Welcome to the AT40 Request links page for Jung Kook. Feel free to click away and make your requests. 

# Profile Image URL
Image_URL: http://www.gravatar.com/avatar/79699862899006b32a2ca0199e862b54?s=400

# Website Background Image
Cover_Image: https://source.unsplash.com/random

# https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY2NTQ3MjA4NQ&ixlib=rb-1.2.1&q=80&w=1080
# https://source.unsplash.com/random

# Request Links
links:
    
    # Z100 New York - Left & Right
  - Name: Z100 New York | Left & Right
    URL: https://tinyurl.com
    Username: AT40-NewYorkNY-Z100-LnR
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # Z100 New York - Stay Alive
  - Name: Z100 New York | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-NewYorkNY-Z100-SA 
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class: fas fa-heartbeat

    # STAR 94.1 Atlanta - Left and Right
  - Name: STAR 94.1 Atlanta | Left and Right
    URL: https://tinyurl.com
    Username: AT40-AtlantaGA-941-LnR 
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # STAR 94.1 Atlanta - Stay Alive
  - Name: STAR 94.1 Atlanta | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-AtlantaGA-941-SA 
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class: 
    
    # 96.7 KISS FM Austin - Left and Right
  - Name: 96.7 KISS FM Austin | Left and Right
    URL: https://tinyurl.com
    Username: AT40-AustinTX-967-LnR 
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fas fa-chevron-left
    Icon-Class-2: fas fa-chevron-right

    # 96.7 KISS FM Austin - Stay Alive
  - Name: 96.7 KISS FM Austin | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-AustinTX-967-SA 
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class:

    # KISS 108 Boston - Left and Right
  - Name: KISS 108 Boston | Left and Right
    URL: https://tinyurl.com
    Username: AT40-BostonMA-108-LnR
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # KISS 108 Boston - Stay Alive
  - Name: KISS 108 Boston | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-BostonMA-108-SA
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class: 

    # 102.7 KIIS FM Los Angeles - Left and Right
  - Name: 102.7 KIIS FM Los Angeles | Left and Right
    URL: https://tinyurl.com
    Username: AT40-LosAngelesCA-1027-LnR 
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # 102.7 KIIS FM Los Angeles - Stay Alive
  - Name: 102.7 KIIS FM Los Angeles | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-LosAngelesCA-1027-SA
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class: 

    # MIX 96.9 Phoenix - Left and Right
  - Name: MIX 96.9 Phoenix | Left and Right
    URL: https://tinyurl.com
    Username: AT40-PhoenixAZ-969-LnR
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # MIX 96.9 Phoenix - Stay Alive
  - Name: MIX 96.9 Phoenix | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-PhoenixAZ-969-SA
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class:

    # Z100 Portland - Left and Right
  - Name: Z100 Portland | Left and Right
    URL: https://tinyurl.com
    Username: AT40-PortandOR-Z100-LnR
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # Z100 Portland - Stay Alive
  - Name: Z100 Portland | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-PortandOR-Z100-SA
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class:

    # KC 101 Hamden - Left and Right
  - Name: KC 101 Hamden | Left and Right
    URL: https://tinyurl.com
    Username: AT40-HamdenCT-101-LnR
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class: fa-solid fa-arrows-left-right

    # KC 101 Hamden - Stay Alive
  - Name: KC 101 Hamden | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-HamdenCT-101-SA 
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class:

    # Y100 Miami - Left and Right
  - Name: Y100 Miami | Left and Right
    URL: https://tinyurl.com
    Username: AT40-MiamiFL-100-LnR 
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class:

    # KY100 Miami - Stay Alive
  - Name: Y100 Miami | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-MiamiFL-100-SA
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class:
    
    # 96.5 KISS FM Cleveland - Left and Right
  - Name: 96.5 KISS FM Cleveland | Left and Right
    URL: https://tinyurl.com
    Username: AT40-ClevelandOH-965-LnR 
    Text_Color: '#FE0DA7'
    Color: '#DFFE03'
    Border_Color: '#FFFFFF'
    Icon-Class:

    # 96.5 KISS FM Cleveland - Stay Alive
  - Name: 96.5 KISS FM Cleveland | Stay Alive
    URL: https://tinyurl.com
    Username: AT40-ClevelandOH-965-SA 
    Text_Color: '#FCFDFF'
    Color: '#010005'
    Border_Color: '#0706C6'
    Icon-Class: fa-regular fa-wave-pulse

    # Twitter - Jung Kook Radio
  - Name: Twitter
    URL: https://twitter.com
    Username: JungkookRadio
    Icon-Class: fab fa-twitter
    Color: '#1da1f2'
    Text_Color: '#ffffff'

    # Contact
  - Name: Email
    URL: 'mailto:hol_1012@yahoo.com'
    Icon-Class: fas fa-envelope
    Color: '#430297'
    Text_Color: '#ffffff'

# Footer - Can be removed entirely by removing 'Yes' or commenting out the code line.
# footer: 'Yes'

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /HIGHonLIFE1012.github.io

# Default Markdown Engine
markdown: kramdown
